### ISSUE TITLE
Adjust toolbar/graph resizing in Analysis tab

### ISSUE THREAD

**Issue by rhinoella** [trisyoungs/duq#1606]
![image](https://github.com/disorderedmaterials/dissolve/assets/101950441/6e70cbac-ac6e-42ec-9cb7-2b3a490694c0)

Toolbar could be scrollable or a dropdown.

**Comment by trisyoungs** [comment]
So this is a (deliberate) byproduct of #1583 where I basically ignored the tool button sizing here since they were the last thing preventing resizing of the GUI when you have limited screen real estate.  I would perhaps suggest that most of the options there could go in a context menu, but I'm ever hopeful that the new Qt3D graphing will be available in the near future, so am always reluctant to spend time on issues such as this!
